#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

 // Home row mods
#define H_A LGUI_T(KC_A)
#define H_S LALT_T(KC_S)
#define H_D LSFT_T(KC_D)
#define H_F LCTL_T(KC_F)
#define H_J LCTL_T(KC_J)
#define H_K RSFT_T(KC_K)
#define H_L LALT_T(KC_L)
#define H_SC RGUI_T(KC_SCLN)

#define KC_TALK HYPR(KC_F4) // talk
#define KC_PTT HYPR(KC_F1) // Push to talk
#define KC_VA HYPR(KC_F2) // Voice activation
#define KC_MU HYPR(KC_F3) // Mute
#define KC_AE RALT(KC_Q)
#define KC_OE RALT(KC_P)
#define KC_UE RALT(KC_Y)
#define KC_SS RALT(KC_S)
#define LSHIF OSM(MOD_LSFT)
#define RSHIF OSM(MOD_RSFT)
#define COPY LCTL(KC_C)
#define PASTE LCTL(KC_V)
#define UNDO LCTL(KC_Z)
#define PIPE S(KC_BSLS)
#define DQUOT S(KC_QUOT)

#define EN2 LT(2, KC_ENT)
#define SPA3 LT(3, KC_SPC)

// Windows presets
#define KC_TASK LGUI(KC_TAB)
#define KC_FLXP LGUI(KC_E)

enum custom_keycodes {
  ARROW = SAFE_RANGE,
  UPDIR
};

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  switch (keycode) {
    case ARROW:
      if (record->event.pressed) {
        SEND_STRING("->");
      }
      return false;
	case UPDIR:
		if (record->event.pressed) {
			SEND_STRING("../");
		}
		return false;
  }
  return true;
}


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_GRV,  KC_1,  KC_2,    KC_3,    KC_4,    KC_5,        			 KC_6,    KC_7,    KC_8,    KC_9,   KC_0,    KC_MU, 
				 KC_ESC,  KC_Q,  KC_W,    KC_E,    KC_R,    KC_T, 				 	 KC_Y,    KC_U,    KC_I,    KC_O,   KC_P,    KC_AE, 
				 KC_TAB,  H_A,   H_S,     H_D,     H_F,     KC_G, 					 KC_H,    H_J,     H_K,     H_L,    H_SC,    KC_OE,
				 LSHIF,   KC_Z,  KC_X,    KC_C,    KC_V,    KC_B,  KC_MUTE, XXXXXXX, KC_N,    KC_M,    KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, 
				            	 COPY,    PASTE,   UNDO,    MO(1), EN2,     KC_BSPC, SPA3,    KC_TALK, KC_PTT,  KC_VA
	),
	[1] = LAYOUT(_______,  _______,  _______,    _______,    _______,    _______,        			 _______,   _______, _______, _______, _______, _______, 
				 _______,  KC_QUOT, KC_LABK,     KC_RABK,    KC_DQUO,    ARROW,                      KC_AMPR,   KC_LPRN, KC_RPRN, KC_PERC, KC_DLR,  KC_UE,
				 _______,  KC_EXLM, KC_MINS,     KC_PLUS,    KC_EQL,     KC_HASH, 			         KC_PIPE,   KC_LBRC, KC_RBRC, KC_GRV,  KC_QUES, KC_SS, 
				 _______,  KC_CIRC, KC_SLSH,     KC_ASTR,    KC_BSLS,    UPDIR,    KC_MUTE, XXXXXXX, KC_TILD,   KC_LCBR, KC_RCBR, KC_UNDS, KC_AT,   RALT(KC_5),
				            	     _______,    _______,    _______,    _______,  _______, _______, _______,   _______, _______, _______
	),
	[2] = LAYOUT(_______,  _______,  _______,    _______,  _______,  _______,        			 _______,  _______, _______, _______, _______, _______, 
				 _______,  _______,  KC_F7,      KC_F8,    KC_F9,    KC_F12,                     _______,  KC_7,    KC_8,    KC_9,    _______, _______,
				 _______,  _______,  KC_F4,      KC_F5,    KC_F6,    KC_F11, 			         _______,  KC_4,    KC_5,    KC_6,    KC_0,    _______, 
				 _______,  _______,  KC_F1,      KC_F2,    KC_F3,    KC_F10,   KC_MUTE, XXXXXXX, _______,  KC_1,    KC_2,    KC_3,    _______, _______,
				            	     _______,    _______,  _______,  _______,  _______, _______, _______,  _______, _______, _______
	),
	[3] = LAYOUT(_______,  _______,  _______,    _______,  _______,    _______,        			  _______,   _______, _______, _______, _______, _______, 
				 _______,  _______,  _______,    _______,  _______,    _______,                   _______,   KC_HOME, KC_UP,   KC_END,  _______, _______,
				 _______,  _______,  KC_LALT,    KC_RSFT,  KC_RCTL,    _______, 			      KC_PGUP,   KC_LEFT, KC_DOWN, KC_RGHT, _______, _______, 
				 _______,  _______,  _______,    _______,  _______,    _______, KC_MUTE, XXXXXXX, KC_PGDN,   _______, _______, _______, _______, _______,
				            	     _______,    _______,  _______,    _______, _______, _______, _______,   _______, _______, _______
	),
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




